---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# RcppChoose

<!-- badges: start -->
<!-- badges: end -->

RcppChoose is an example of project that combines two parts, 
C++ code ([libChoose/](libChoose/)) and R package ([rpackage/](rpackage/)).

## Install

```
# 1. compile the c++ library 
# - output: libChoose/libChoose.a
pushd libChoose/
make
popd

# 2. prepare Makefile for R package
# - output: rpkg/RcppChoose/src/Makevars
pushd rpkg
autoconf
./configure
popd

# 3. check R package is ready to use 
Rscript --slave -e "devtools::load_all('rpkg/RcppChoose')"
```

## Usage

```{r load}
devtools::load_all("rpkg/RcppChoose")
```

## Example

This is a basic example which shows you how to choose `k` out of `n` numbers.

```{r example}
library(RcppChoose)

# 1. choose: base R vs. RcppChoose implementation
# 1a. choose(10, 5)
choose(10, 5)
rcpp_choose(10, 5)
# 1b. choose(40, 20)
choose(40, 20)
rcpp_choose(40, 20)

# 100 samples of sets of size k = 500 out of n = 1000
rcpp_nchoosek_sample(1000, 500, 100)
```

