// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_nchoosek_sample
int rcpp_nchoosek_sample(int n, int k, int s);
RcppExport SEXP _RcppChoose_rcpp_nchoosek_sample(SEXP nSEXP, SEXP kSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nchoosek_sample(n, k, s));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_nchoosek_rec
int rcpp_nchoosek_rec(int n, int k);
RcppExport SEXP _RcppChoose_rcpp_nchoosek_rec(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_nchoosek_rec(n, k));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_choose
int rcpp_choose(int n, int k);
RcppExport SEXP _RcppChoose_rcpp_choose(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_choose(n, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppChoose_rcpp_nchoosek_sample", (DL_FUNC) &_RcppChoose_rcpp_nchoosek_sample, 3},
    {"_RcppChoose_rcpp_nchoosek_rec", (DL_FUNC) &_RcppChoose_rcpp_nchoosek_rec, 2},
    {"_RcppChoose_rcpp_choose", (DL_FUNC) &_RcppChoose_rcpp_choose, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppChoose(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
