# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_nchoosek_sample <- function(n, k, s) {
    .Call(`_RcppChoose_rcpp_nchoosek_sample`, n, k, s)
}

rcpp_nchoosek_rec <- function(n, k) {
    .Call(`_RcppChoose_rcpp_nchoosek_rec`, n, k)
}

rcpp_choose <- function(n, k) {
    .Call(`_RcppChoose_rcpp_choose`, n, k)
}

